apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: securing-web
# stringData keeps values in cleartext and avoids manual base64 encoding
# Replace placeholders before applying in shared clusters
stringData:
  AUTH0_CLIENT_ID: REPLACE_WITH_YOUR_CLIENT_ID
  AUTH0_CLIENT_SECRET: REPLACE_WITH_YOUR_CLIENT_SECRET

